# Generated by Django 3.2.7 on 2021-10-30 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('P', 'Personal'), ('O', 'Official')], default='P', max_length=1)),
                ('Description', models.CharField(max_length=250)),
                ('Owner', models.CharField(max_length=80)),
                ('Status', models.CharField(choices=[('C', 'Completed'), ('S', 'Start'), ('W', 'WIP')], default='P', max_length=1)),
                ('Start_dt', models.DateField(default=datetime.date.today)),
                ('End_dt', models.DateField()),
            ],
        ),
    ]
