# Generated by Django 3.2.7 on 2021-11-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='priority',
            new_name='Priority',
        ),
    ]
