# Generated by Django 3.2.7 on 2021-11-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
