# Generated by Django 3.2.7 on 2021-11-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
