# Generated by Django 3.2.7 on 2021-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_note_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
