# Generated by Django 3.2.7 on 2022-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='meaning',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
