# Generated by Django 3.2.7 on 2022-02-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_vocab_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
